# This is a basic workflow to help you get started with Actions

name: Subflow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
        description: First input (not a secret)
      environment:
        required: true
        type: string
        description: name of the environment
    secrets:
      secret1:
        required: true
        description: super secret 1
      secret2:
        required: true
        description: super secret 2


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Echo secrets
        env:
          i1: ${{ inputs.input1 }}
          s1: ${{ secrets.secret1 }}
          s2: ${{ secrets.secret2 }}
        run: |
          echo "Input 1: $i1"
          
          if [$s1 = "Secret #1 from prod"]
          then
            echo "Got secret #2 from prod"
          elif [$s1 = "Secret #1 from preprod"]
          then
            echo "Got secret #1 from preprod"
          elif [$s1 = "Secret #1 from dev"]
          then
            echo "Got secret #1 from dev"
          else
            echo "No match for s1"
          fi          

          if [$s2 = "Secret #2 from prod"]
          then
            echo "Got secret #2 from prod"
          elif [$s2 = "Secret #2 from preprod"]
          then
            echo "Got secret #2 from preprod"
          elif [$s2 = "Secret #2 from dev"]
          then
            echo "Got secret #2 from dev"
          else
            echo "no match for s2"
          fi          
